import type { Moment } from './theme';

export const SAMPLE_MOMENTS: Moment[] = [
  {
    id: '1',
    title: 'Last time I carried Mia to bed',
    detail: 'She fell asleep mid-sentence asking for water. I just stood there for a minute.',
    date: '2025-06-26',
    category: 'parenthood',
    mood: 'bittersweet',
    hasPhoto: false,
    hasVoiceNote: false,
    createdAt: '2025-06-26T22:30:00Z',
  },
  {
    id: '2',
    title: 'Last time in my hometown',
    detail: "Before Grandma's house sold. Stood in the kitchen where she made Sunday dinners for 40 years.",
    date: '2025-06-12',
    category: 'family',
    mood: 'nostalgic',
    hasPhoto: true,
    hasVoiceNote: false,
    createdAt: '2025-06-12T14:00:00Z',
  },
  {
    id: '3',
    title: 'Last jam with the band',
    detail: 'Before Ravi moved to Berlin. We played until 2am and no one wanted to leave.',
    date: '2024-11-03',
    category: 'friendships',
    mood: 'peaceful',
    hasVoiceNote: true,
    hasPhoto: false,
    createdAt: '2024-11-03T19:00:00Z',
  },
  {
    id: '4',
    title: 'Sunrise with Dad at the pier',
    detail: 'He said he was proud of me. First time he ever said it out loud like that.',
    date: '2024-08-17',
    category: 'family',
    mood: 'bittersweet',
    hasPhoto: true,
    hasVoiceNote: false,
    createdAt: '2024-08-17T06:30:00Z',
  },
  {
    id: '5',
    title: 'Solo trip to Kyoto',
    detail: 'First time truly alone abroad. Ate ramen at midnight and cried a little. Felt free.',
    date: '2024-03-22',
    category: 'travel',
    mood: 'peaceful',
    hasPhoto: true,
    hasVoiceNote: false,
    createdAt: '2024-03-22T10:00:00Z',
  },
  {
    id: '6',
    title: 'Last run before the surgery',
    detail: "Felt the road under my feet. Didn't know if I'd feel it the same way again.",
    date: '2024-01-08',
    category: 'self',
    mood: 'melancholic',
    hasVoiceNote: true,
    hasPhoto: false,
    createdAt: '2024-01-08T07:00:00Z',
  },
  {
    id: '7',
    title: "Mom taught me her pasta recipe",
    detail: 'Her hands guiding mine over the dough. Three generations in one afternoon.',
    date: '2023-12-25',
    category: 'family',
    mood: 'grateful',
    hasPhoto: true,
    hasVoiceNote: false,
    createdAt: '2023-12-25T13:00:00Z',
  },
  {
    id: '8',
    title: 'Last high school reunion',
    detail: 'We all look so different now. Laughed about things that once felt like the end of the world.',
    date: '2023-10-14',
    category: 'friendships',
    mood: 'nostalgic',
    hasPhoto: false,
    hasVoiceNote: false,
    createdAt: '2023-10-14T18:00:00Z',
  },
  {
    id: '9',
    title: 'Eli said "carry me" for the last time',
    detail: "I didn't know it was the last time until weeks later. He just got up and walked.",
    date: '2023-07-19',
    category: 'parenthood',
    mood: 'bittersweet',
    hasPhoto: false,
    hasVoiceNote: false,
    createdAt: '2023-07-19T20:00:00Z',
  },
  {
    id: '10',
    title: 'Quit the corporate job',
    detail: 'Walked out feeling lighter than I had in years. Terrified. Alive.',
    date: '2023-04-01',
    category: 'milestones',
    mood: 'joyful',
    hasPhoto: false,
    hasVoiceNote: false,
    createdAt: '2023-04-01T17:00:00Z',
  },
  {
    id: '11',
    title: 'Watched the old house get demolished',
    detail: 'Stood there with childhood photos in my pocket. Some endings are permanent.',
    date: '2022-11-30',
    category: 'family',
    mood: 'melancholic',
    hasPhoto: true,
    hasVoiceNote: false,
    createdAt: '2022-11-30T14:00:00Z',
  },
  {
    id: '12',
    title: 'Played guitar at the open mic',
    detail: 'The crowd went quiet. Not because it was bad — because it was honest.',
    date: '2022-08-13',
    category: 'self',
    mood: 'joyful',
    hasVoiceNote: true,
    hasPhoto: false,
    createdAt: '2022-08-13T21:00:00Z',
  },
  {
    id: '13',
    title: 'Road trip with Jake and Priya',
    detail: 'Before Priya left for Australia. Sang badly to every song. No one cared.',
    date: '2022-05-28',
    category: 'friendships',
    mood: 'grateful',
    hasPhoto: true,
    hasVoiceNote: false,
    createdAt: '2022-05-28T09:00:00Z',
  },
  {
    id: '14',
    title: "Mia's first steps",
    detail: 'She looked at me like she had just discovered she could fly. I caught every second.',
    date: '2021-10-03',
    category: 'parenthood',
    mood: 'joyful',
    hasPhoto: true,
    hasVoiceNote: true,
    createdAt: '2021-10-03T16:00:00Z',
  },
  {
    id: '15',
    title: 'Anniversary trip to Florence',
    detail: '10 years. We sat at the same café we found on our first trip and ordered the same wine.',
    date: '2021-06-15',
    category: 'travel',
    mood: 'grateful',
    hasPhoto: true,
    hasVoiceNote: false,
    createdAt: '2021-06-15T12:00:00Z',
  },
  {
    id: '16',
    title: "Last therapy session with Dr. Nair",
    detail: 'She said I was ready. I still cried on the way out.',
    date: '2021-03-08',
    category: 'self',
    mood: 'bittersweet',
    hasPhoto: false,
    hasVoiceNote: false,
    createdAt: '2021-03-08T15:00:00Z',
  },
];
